In [1]:
# Import library

import numpy as np

In [2]:
# Inputs

# Creating input values as a matrix not as a vector
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])

In [3]:
# Chcking the shape of the inputs

inputs.shape

(4, 2)

In [4]:
# Outputs

outputs = np.array([0, 0, 0, 1])

In [6]:
# Weights

# one weight for x1 and one for x2
weights = np.array([0.0, 0.0])

In [7]:
learning_rate = 0.1

In [8]:
# Step function

# This is our Activation function

def step_function(sum):
  if (sum >= 1):
    #print(f'The Sum of Weights is Greater or equal to 1')
    return 1
  else:
        #print(f'The Sum of Weights is NOT > or = to 1')
        return 0

In [9]:
# Process output

def cal_output(instance):
  sum_func = instance.dot(weights)
  return step_function(sum_func)

In [10]:
cal_output(np.array([[1,1]]))

# 0

0

In [11]:
# Check the number of outputs

len(outputs)

# 4

4

In [12]:
# Checking the index of the input at postion 3 ..
# this is the last inpute value
inputs[3]

# array([1, 1])

array([1, 1])

In [14]:
def train():
    #
    total_error_value = 1
    # While the total_error_value is not equal to zero. we are asumming that at the start of running our network there will be no zero
    while (total_error_value != 0):
        #making the total_error 0 so we can do other calculations
        total_error_value = 0
        #Looping into each row of the dataset (remember indexing in python starts at zero hence 0-3 which are 4 values)
        for i in range(len(outputs)):
            #Calculating predictions
            prediction = cal_output(inputs[i])
            # Calculating the absolute value of the error
            error = abs(outputs[i] - prediction)
            #Updating the error
            total_error_value  += error

            if error > 0:
                for j in range(len(weights)):
                    #updating the weights for x1 and x2
                    weights[j] = weights[j] + (learning_rate * inputs[i][j] * error)
                    print('Weight updated to: ' + str(weights[j]))
        print('Total error Value: ' + str(total_error_value))

In [15]:
train()

Weight updated to: 0.1
Weight updated to: 0.1
Total error Value: 1
Weight updated to: 0.2
Weight updated to: 0.2
Total error Value: 1
Weight updated to: 0.30000000000000004
Weight updated to: 0.30000000000000004
Total error Value: 1
Weight updated to: 0.4
Weight updated to: 0.4
Total error Value: 1
Weight updated to: 0.5
Weight updated to: 0.5
Total error Value: 1
Total error Value: 0


In [16]:
# Classification

# Now we have the final weights that will be used to classify new instances of the data after training.

weights

# array([0.5, 0.5])

array([0.5, 0.5])

In [17]:
cal_output(np.array([0,0]))

# 0

0

In [19]:
cal_output(np.array([0,1]))

# 0

0

In [20]:
cal_output(np.array([1,0]))

# 0

0

In [21]:
cal_output(np.array([1,1]))

# 1

1